import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Samvera - a vibrant and welcoming community developing repository software tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://samvera.org"><img src="https://samvera.org/wp-content/uploads/2017/06/samvera-logo-tm.svg" alt="Samvera Repository" /></a>
        </h1>
      </main>

      <footer className={styles.footer}>
          &copy; 2022 Samvera.
      </footer>
    </div>
  )
}
